language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
#caches node_modules for faster ci process
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
#nohup === 'no hang up' => if command line gets closed, keep running process
# '&' => runs the process in the background shell
# 'sleep 3' gives us time to start server up (buffer)